config/routes.rb
require 'sidekiq/web'

Lagotto::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "docs#index"

  # constraints is added to allow dot in the url (doi is used to show article)
  resources :works, constraints: { :id => /.+?/, :format => /html|js/ }
  resources :sources, param: :name do
    resources :publisher_options, only: [:show, :edit, :update]
  end
  resources :users
  resources :publishers, param: :member_id
  resources :docs, :only => [:index, :show], :constraints => { :id => /[0-z\-\.\(\)]+/ }
  resources :alerts
  resources :api_requests
  resources :filters
  resources :status, :only => [:index]

  get "heartbeat", to: "heartbeat#show", defaults: { format: "json" }
  get "oembed", to: "oembed#show"

  get "/files/alm_report.zip", to: redirect("/files/alm_report.zip")

  get "/api", to: "api/index#index"

  namespace :api, defaults: { format: "json" } do
    namespace :v3 do
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }, only: [:index, :show]
    end

    namespace :v4 do
      resources :alerts, :constraints => { :format=> false }
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }
    end

    namespace :v5 do
      resources :works, path: "articles", constraints: { :id => /.+?/ }, only: [:index]
      resources :sources, only: [:index, :show], param: :name
      resources :status, only: [:index]
      resources :api_requests, only: [:index]
      resources :publishers, only: [:index], param: :member_id
    end
  end

  # redirect from old admin namespace
  get "/admin/:name", to: redirect("/%{name}")
  get "/admin/", to: redirect("/status")

  # rescue routing errors
  match "*path", to: "alerts#routing_error", via: [:get, :post]
end

app/models/article.rb
require 'cgi'
require 'addressable/uri'
require "builder"

class Article < ActiveRecord::Base
  strip_attributes

  # include HTTP request helpers
  include Networkable

  # include helper module for DOI resolution
  include Resolvable

  belongs_to :publisher, primary_key: :crossref_id
  has_many :retrieval_statuses, :dependent => :destroy
  has_many :sources, :through => :retrieval_statuses
  has_many :alerts
  has_many :api_responses

  validates :uid, :title, :presence => true
  validates :doi, :uniqueness => true, :format => { :with => DOI_FORMAT }, :allow_nil => true
  validates :year, :numericality => { :only_integer => true }, :inclusion => { :in => 1650..(Time.zone.now.year), :message => "should be between 1650 and #{Time.zone.now.year}" }
  validate :validate_published_on, if: proc { |article| article.year.present? }

  before_validation :sanitize_title
  after_create :create_retrievals

  scope :query, ->(query) { where("doi like ?", "#{query}%") }
  scope :last_x_days, ->(duration) { where("published_on >= ?", Time.zone.now.to_date - duration.days) }
  scope :has_events, -> { includes(:retrieval_statuses)
    .where("retrieval_statuses.event_count > ?", 0)
    .references(:retrieval_statuses) }
  scope :by_source, ->(source_id) { joins(:retrieval_statuses)
    .where("retrieval_statuses.source_id = ?", source_id) }

  def self.from_uri(id)
    return nil if id.nil?

    id = id.gsub("%2F", "/")
    id = id.gsub("%3A", ":")

    case
    when id.starts_with?("http://dx.doi.org/") then { doi: id[18..-1] }
    when id.starts_with?("info:doi/")          then { doi: CGI.unescape(id[9..-1]) }
    when id.starts_with?("info:pmid/")         then { pmid: id[10..-1] }
    when id.starts_with?("info:pmcid/PMC")     then { pmcid: id[14..-1] }
    when id.starts_with?("info:pmcid/")        then { pmcid: id[11..-1] }
    when id.starts_with?("info:mendeley/")     then { mendeley_uuid: id[14..-1] }
    else { uid.to_sym => id }
    end
  end

  def self.to_uri(id, escaped=true)
    return nil if id.nil?
    unless id.starts_with? "info:"
      id = "info:#{uid}/" + from_uri(id).values.first
    end
    id
  end

  def self.to_url(doi)
    return nil if doi.nil?
    return doi if doi.starts_with? "http://dx.doi.org/"
    "http://dx.doi.org/#{from_uri(doi).values.first}"
  end

  def self.clean_id(id)
    if id.starts_with? "10."
      Addressable::URI.unencode(id)
    elsif id.starts_with? "PMC"
      id[3..-1]
    else
      id
    end
  end

  def self.uid
    ENV['UID']
  end

  def self.uid_as_sym
    uid.to_sym
  end

  def self.validate_format(id)
    case ENV['UID']
    when "doi"
      id =~ DOI_FORMAT
    else
      true
    end
  end

  def self.find_or_create(params)
    self.create!(params)
  rescue ActiveRecord::RecordInvalid, ActiveRecord::RecordNotUnique => e
    # update title and/or date if article exists
    # raise an error for other RecordInvalid errors such as missing title
    if e.message.start_with?("Mysql2::Error: Duplicate entry", "Validation failed: Doi has already been taken")
      article = Article.where(doi: params[:doi]).first
      article.update_attributes(params)
      article
    else
      Alert.create(:exception => "",
                   :class_name => "ActiveRecord::RecordInvalid",
                   :message => "#{e.message} for doi #{params[:doi]}.",
                   :target_url => "http://api.crossref.org/works/#{params[:doi]}")
      nil
    end
  end

  def self.per_page
    50
  end

  def self.count_all
    if ActionController::Base.perform_caching
      status_update_date = Rails.cache.read('status:timestamp')
      Rails.cache.read("status/articles_count/#{status_update_date}").to_i
    else
      Article.count
    end
  end

  def self.queue_article_delete(publisher_id)
    if publisher_id == "all"
      delay(priority: 2, queue: "article-delete-queue").destroy_all
    elsif publisher_id.present?
      delay(priority: 2, queue: "article-delete-queue")
        .destroy_all(publisher_id: publisher_id)
    end
  end

  def uid
    send(self.class.uid)
  end

  def uid_escaped
    CGI.escape(uid)
  end

  def to_param
    self.class.to_uri(uid)
  end

  def events_count
    @events_count ||= retrieval_statuses.reduce(0) { |sum, r| sum + r.event_count }
  end

  def doi_escaped
    CGI.escape(doi) if doi.present?
  end

  def doi_as_url
    Addressable::URI.encode("http://dx.doi.org/#{doi}")  if doi.present?
  end

  def doi_prefix
    doi[/^10\.\d{4,5}/]
  end

  def get_url
    return true if canonical_url.present?
    return false unless doi.present?

    url = get_canonical_url(doi_as_url, article_id: id)

    if url.present? && url.is_a?(String)
      update_attributes(:canonical_url => url)
    else
      false
    end
  end

  # call Pubmed API to get missing identifiers
  # update article if we find a new identifier
  def get_ids
    ids = { doi: doi, pmid: pmid, pmcid: pmcid }
    missing_ids = ids.reject { |k, v| v.present? }
    return true if missing_ids.empty?

    result = get_persistent_identifiers(uid)
    return true if result.blank?

    # remove PMC prefix
    result['pmcid'] = result['pmcid'][3..-1] if result['pmcid']

    new_ids = missing_ids.reduce({}) do |hash, (k, v)|
      val = result[k.to_s]
      hash[k] = val if val.present? && val != "0"
      hash
    end
    return true if new_ids.empty?

    update_attributes(new_ids)
  end

  def all_urls
    urls = []
    urls << doi_as_url if doi.present?
    urls << canonical_url if canonical_url.present?
    urls
  end

  def canonical_url_escaped
    CGI.escape(canonical_url)
  end

  def title_escaped
    CGI.escape(title.to_str).gsub("+", "%20")
  end

  def signposts
    @signposts ||= sources.pluck(:name, :event_count, :events_url)
  end

  def event_count(name)
    signposts.reduce(0) { |sum, source| source[0] == name ? source[1].to_i : sum }
  end

  def events_url(name)
    signposts.reduce(nil) { |sum, source| source[0] == name ? source[2] : sum }
  end

  def mendeley_url
    @mendeley_url ||= events_url("mendeley")
  end

  def citeulike_url
    @citeulike_url ||= events_url("citeulike")
  end

  def views
    @views || event_count("pmc") + event_count("counter")
  end

  def shares
    @shares ||= event_count("facebook") + event_count("twitter") + event_count("twitter_search")
  end

  def bookmarks
    @bookmarks ||= event_count("citeulike") + event_count("mendeley")
  end

  def citations
    @citations ||= Source.installed.where(name: "scopus").first ? event_count("scopus") : event_count("crossref")
  end

  alias_method :viewed, :views
  alias_method :saved, :bookmarks
  alias_method :discussed, :shares
  alias_method :cited, :citations

  def issued
    { "date-parts" => [[year, month, day].reject(&:blank?)] }
  end

  def issued_date
    date_parts = issued["date-parts"].first
    date = Date.new(*date_parts)

    case date_parts.length
    when 1 then date.strftime("%Y")
    when 2 then date.strftime("%B %Y")
    when 3 then date.strftime("%B %-d, %Y")
    end
  end

  def update_date_parts
    return nil unless published_on

    write_attribute(:year, published_on.year)
    write_attribute(:month, published_on.month)
    write_attribute(:day, published_on.day)
  end

  def update_date
    updated_at.nil? ? nil : updated_at.utc.iso8601
  end

  private

  # Use values from year, month, day for published_on
  # Uses  "01" for month and day if they are missing
  def validate_published_on
    date_parts = [year, month, day].reject(&:blank?)
    published_on = Date.new(*date_parts)
    if published_on > Date.today
      errors.add :published_on, "is a date in the future"
    else
      write_attribute(:published_on, published_on)
    end
  rescue ArgumentError
    errors.add :published_on, "is not a valid date"
  end

  def sanitize_title
    self.title = ActionController::Base.helpers.sanitize(title)
  end

  def create_retrievals
    # Create an empty retrieval record for every installed source for the new article
    Source.installed.each do |source|
      RetrievalStatus.where(article_id: id, source_id: source.id).first_or_create
    end
  end
end

app/controllers/api/v4/articles_controller.rb
class Api::V4::ArticlesController < Api::V4::BaseController
  # include article controller methods
  include Articable

  before_filter :load_article, only: [:update, :destroy]

  def create
    @article = Article.new(safe_params)
    authorize! :create, @article

    if @article.save
      @success = "Article created."
      render "success", :status => :created
    else
      @error = @article.errors
      render "error", :status => :bad_request
    end
  end

  def update
    authorize! :update, @article

    if @article.blank?
      @error = "No article found."
      render "error", :status => :not_found
    elsif @article.update_attributes(safe_params)
      @success = "Article updated."
      render "success", :status => :ok
    else
      @error = @article.errors
      render "error", :status => :bad_request
    end
  end

  def destroy
    authorize! :destroy, @article

    if @article.blank?
      @error = "No article found."
      render "error", :status => :not_found
    elsif @article.destroy
      @success = "Article deleted."
      render "success", :status => :ok
    else
      @error = "An error occured."
      render "error", :status => :bad_request
    end
  end

  private

  def safe_params
    params.require(:article).permit(:doi, :title, :pmid, :pmcid, :mendeley_uuid, :canonical_url, :year, :month, :day)
  end
end

app/views/admin/articles/_index.html.erb
<% if can?(:manage, Article) and (controller.action_name == "new" or (controller.action_name == "create" and !@article.errors.empty?)) %>

  <%= simple_form_for @article, :url => admin_articles_path, :html => { :remote => true } do |f| %>
    <fieldset>
      <legend>New Article</legend>

      <%= f.input :title, :input_html => { :rows => 2 } %>
      <%= f.input :doi, :label => 'DOI' %>
      <%= f.input :pmid, :label => 'PubMed ID' %>
      <%= f.input :pmcid, :label => 'PubMed Central ID' %>
      <%= f.input :mendeley_uuid, :label => 'Mendeley UUID' %>
      <%= f.input :canonical_url, :label => 'Canonical URL' %>
      <%= f.input :published_on, label: "Publication Date" do %>
        <%= f.input_field :day, as: :day %>
        <%= f.input_field :month, as: :month %>
        <%= f.input_field :year, as: :year %>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save ", class: "btn btn-default" %>
        <%= link_to 'Cancel', admin_articles_path, { :remote => true, :class => 'btn' } %>
      </div>
    </fieldset>
  <% end %>

<% else %>
  <div class="page-header">
    <div class="btn-toolbar pull-right">
      <% if can?(:manage, Article) %>
        <div class="btn-group btn-group-sm">
          <%= link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe, new_admin_article_path, { :remote => true, :id => "new_article", :class => 'btn btn-default' } %>
        </div>
      <% end %>
      <% if can? :read, Alert %>
        <div class="btn-group btn-group-sm" id="article-alerts">
          <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-filter"></span> <%= @class_name.nil? ? "All Articles" : h(@class_name) %> <span class="caret"></span></a>
          <ul class="dropdown-menu pull-right">
            <li><%= link_to "All Articles", articles_path(:q => params[:q]) %></li>
            <li class="divider"></li>
            <li><%= link_to "All Alerts", articles_path(:class_name => "All Alerts", :q => params[:q]) %></li>
            <li class="divider"></li>
            <% article_alerts.each do |alert| %>
              <li><%= link_to h(alert), articles_path(:class_name => alert, :q => params[:q]) %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="btn-group btn-group-sm" id="article-order">
        <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-sort"></span> <%= @order.nil? || Source.find_by_name(@order).nil? ? "Date" : h(Source.active.select { |s| s.name == @order }.first.display_name) %> <span class="caret"></span></a>
        <ul class="dropdown-menu pull-right">
          <li><%= link_to "Date", articles_path(q: params[:q], class_name: params[:class_name]) %></li>
            <% Group.order("id").each do |group| %>
              <% unless group.sources.active.empty? %>
                <li class="divider"></li>
                <% group.sources.active.each do |source| %>
                  <li><%= link_to h(source.display_name), articles_path(q: params[:q], class_name: params[:class_name], order: source.name) %></li>
                <% end %>
              <% end %>
            <% end %>
        </ul>
      </div>
    </div>
     <h1 id="api_key" data-api_key="<%= CONFIG[:api_key] %>" data-uid_type="<%= CONFIG[:uid] %>" data-page="<%= @page %>" data-q="<%= @q %>" data-class_name="<%= @class_name %>" data-order="<%= @order %>">Articles
    <% unless params[:q].blank? %>
      <small>with <em><%= params[:q] %></em> in the DOI<%= Article.has_many? ? "" : " or Title" %></small>
    <% end %>
    </h1>
  </div>

  <div class="search">
    <%= form_tag(articles_path, :method => "get", :class => "form-inline", :role => "form") do %>
       <div class="form-group">
        <%= search_field_tag :q, params[:q], :placeholder => Article.has_many? ? "Search by DOI" : "Search by DOI or Title", :class => "form-control" %>
      </div>
      <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
      <% unless params[:q].blank? %>
        <%= link_to "clear", articles_path, :class => "btn" %>
      <% end %>
    <% end %>
  </div>

  <div id="results"></div>
  <div class="text-muted" id="loading-results">Loading page … <%= image_tag "spinner.gif" %></div>

  <%= javascript_include_tag 'articles/index' %>
<% end %>

app/views/admin/articles/_more.html.erb
<% unless @article.retrieval_statuses.empty? %>
  <div class="panel-group" id="retrieval_status">
    <% @article.retrieval_statuses.with_sources.each do |status| %>
      <% if !status.source.nil? %>
        <div class="panel <%= (status.retrieved_at > '1970-01-01' || status.source.retired?) ? 'panel-default' : 'panel-warning' %>" id="<%= status.source.name %>">
          <%= render partial: 'admin/articles/source', locals: { status: status } %>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <div class="alert alert-info">There are currently no events</div>
<% end %>

app/views/admin/articles/_show.html.erb
<% if can?(:manage, Article) and (controller.action_name == "edit" or (controller.action_name == "update" and !@article.errors.empty?)) %>

  <%= simple_form_for @article, :url => admin_article_path(@article), :html => { :role => "form", :remote => true } do |f| %>
    <fieldset>
      <legend>Edit Article</legend>

      <%= f.input :title, :input_html => { :rows => 2 } %>
      <%= f.input :doi, :label => 'DOI', :disabled => CONFIG[:uid] == "doi" %>
      <%= f.input :pmid, :label => 'PubMed ID', :disabled => CONFIG[:uid] == "pmid" %>
      <%= f.input :pmcid, :label => 'PubMed Central ID', :disabled => CONFIG[:uid] == "pmcid" %>
      <%= f.input :mendeley_uuid, :label => 'Mendeley UUID' %>
      <%= f.input :canonical_url, :label => 'Canonical URL' %>
      <%= f.input :published_on, label: "Publication Date" do %>
        <%= f.input_field :day, as: :day %>
        <%= f.input_field :month, as: :month %>
        <%= f.input_field :year, as: :year %>
      <% end %>

      <div class="form-group">
        <%= f.submit "Save ", class: "btn btn-default" %>
        <%= link_to 'Cancel', admin_article_path(@article), { :remote => true, :class => 'btn' } %>
      </div>
    </fieldset>
  <% end %>

<% else %>
  <div class="page-header">
    <h1 id="api_key" data-api_key="<%= CONFIG[:api_key] %>" data-uid_type="<%= CONFIG[:uid] %>" data-uid="<%= @article.uid %>">
      <% if can?(:manage, Article) %>
        <div class="btn-toolbar pull-right">
          <div class="btn-group btn-group-sm">
            <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_admin_article_path(@article), { :remote => true, :class => 'btn btn-default' } %>
          </div>
          <div class="btn-group btn-group-sm">
            <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, admin_article_path(@article), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-default' %>
          </div>
        </div>
      <% end %>
      <%= h@article.title %>
    </h1>
  </div>

  <dl class="dl-horizontal">
    <dt>Publication Date</dt>
    <dd><%= l @article.published_on, format: date_format(@article) %></dd>
    <% if @article.doi.present? %>
      <dt>DOI</dt>
      <dd class="doi" %><%= link_to h(@article.doi), @article.doi_as_url %></dd>
    <% end %>
    <% if @article.pmid.present? %>
      <dt>PubMed ID</dt>
      <dd id="pmid" data-pmid="<%= @article.pmid %>"><%= link_to @article.pmid, "http://www.ncbi.nlm.nih.gov/pubmed/#{@article.pmid}" %></dd>
    <% end %>
    <% if @article.pmcid.present? %>
      <dt>PubMed Central ID</dt>
      <dd id="pmcid" data-pmcid="<%= @article.pmcid %>"><%= link_to "PMC#{@article.pmcid}", "http://www.ncbi.nlm.nih.gov/pmc/articles/PMC#{@article.pmcid}" %></dd>
    <% end %>
    <% if @article.mendeley_uuid %>
      <dt>Mendeley UUID</dt>
      <dd id="mendeley_uuid" data-mendeley_uuid="<%= @article.mendeley_uuid %>"><%= @article.mendeley_uuid %></dd>
    <% end %>
    <dt>URLs</dt>
    <dd>
      <% if @article.canonical_url.present? %>
        <%= link_to h(@article.canonical_url), @article.canonical_url %><br/>
      <% end %>
      <% if @article.pmid.present? %>
        <%= link_to "http://europepmc.org/abstract/MED/#{@article.pmid}", "http://europepmc.org/abstract/MED/#{@article.pmid}" %><br/>
      <% end %>
      <% if @article.mendeley_url.present? %>
        <%= link_to h(@article.mendeley_url), @article.mendeley_url %><br/>
      <% end %>
      <% if @article.citeulike_url.present? %>
        <%= link_to h(@article.citeulike_url), @article.citeulike_url %><br/>
      <% end %>
    </dd>
  </dl>

  <% if can? :read, Alert %>
    <div id="alert-error-message">
      <%= render :partial => 'admin/articles/alert_message' %>
    </div>
  <% end %>

  <ul class="nav nav-tabs">
    <li class="active"><a href="#metrics" data-toggle="tab" title="Metrics">Metrics</a></li>
    <li><a href="#events" data-toggle="tab" title="Events">Events</a></li>
    <li><a href="#more" data-toggle="tab" title="More">Details</a></li>
    <% if can? :read, Alert %>
      <li><a href="#alert" data-toggle="tab" title="Alerts">Alerts</a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="metrics">
      <%= render :partial => 'admin/articles/metrics' %>
    </div>
    <div class="tab-pane" id="events">
      <%= render :partial => 'admin/articles/events' %>
    </div>
    <div class="tab-pane" id="more">
      <%= render :partial => 'admin/articles/more' %>
    </div>
    <div class="tab-pane" id="alert">
      <%= render :partial => 'admin/articles/alert' %>
    </div>
  </div>
<% end %>