config/routes.rb
require 'sidekiq/web'

Lagotto::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }

  root :to => "docs#index"

  # constraints is added to allow dot in the url (doi is used to show article)
  resources :works, constraints: { :id => /.+?/, :format => /html|js/ }
  resources :sources, param: :name do
    resources :publisher_options, only: [:show, :edit, :update]
  end
  resources :users
  resources :publishers, param: :member_id
  resources :docs, :only => [:index, :show], :constraints => { :id => /[0-z\-\.\(\)]+/ }
  resources :alerts
  resources :api_requests
  resources :filters
  resources :status, :only => [:index]

  get "heartbeat", to: "heartbeat#show", defaults: { format: "json" }
  get "oembed", to: "oembed#show"

  get "/files/alm_report.zip", to: redirect("/files/alm_report.zip")

  get "/api", to: "api/index#index"

  namespace :api, defaults: { format: "json" } do
    namespace :v3 do
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }, only: [:index, :show]
    end

    namespace :v4 do
      resources :alerts, :constraints => { :format=> false }
      resources :works, path: "articles", constraints: { :id => /.+?/, :format=> false }
    end

    namespace :v5 do
      resources :works, path: "articles", constraints: { :id => /.+?/ }, only: [:index]
      resources :sources, only: [:index, :show], param: :name
      resources :status, only: [:index]
      resources :api_requests, only: [:index]
      resources :publishers, only: [:index], param: :member_id
    end
  end

  # redirect from old admin namespace
  get "/admin/:name", to: redirect("/%{name}")
  get "/admin/", to: redirect("/status")

  # rescue routing errors
  match "*path", to: "alerts#routing_error", via: [:get, :post]
end

app/models/user.rb
class User < ActiveRecord::Base
  # include HTTP request helpers
  include Networkable

  belongs_to :publisher, primary_key: :member_id
  has_and_belongs_to_many :reports

  before_save :ensure_authentication_token
  before_create :set_first_user

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:persona, :cas, :github, :orcid]

  validates :name, presence: true
  validates :email, uniqueness: true, allow_blank: true

  scope :query, ->(query) { where("name like ? OR email like ? OR authentication_token like ?", "%#{query}%", "%#{query}%", "%#{query}%") }
  scope :ordered, -> { order("current_sign_in_at DESC") }

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
    end
  end

  # fetch additional user information for cas strategy
  # use Auth Hash Schema https://github.com/intridea/omniauth/wiki/Auth-Hash-Schema
  def self.fetch_raw_info(uid)
    return { error: "no uid provided" } if uid.nil?

    url = "#{ENV['CAS_INFO_URL']}/#{uid}"
    profile = User.new.get_result(url) || { error: "no profile returned" }
    return profile if profile[:error]

    { name: profile.fetch("realName", uid),
      email: profile.fetch("email", nil),
      nickname: profile.fetch("displayName", nil),
      first_name: profile.fetch("givenNames", nil),
      last_name: profile.fetch("surname", nil) }
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    email = conditions.delete(:email)
    where(conditions).where(["lower(email) = :value", { :value => email.strip.downcase }]).first
  end

  def self.per_page
    15
  end

  # Helper method to check for admin user
  def is_admin?
    role == "admin"
  end

  # Helper method to check for admin or staff user
  def is_admin_or_staff?
    ["admin", "staff"].include?(role)
  end

  # Use different cache key for admin or staff user
  def cache_key
    is_admin_or_staff? ? "1" : "2"
  end

  def api_key
    authentication_token
  end

  def email_with_name
    if email && name != email
      "#{name} <#{email}>"
    else
      email
    end
  end

  protected

  def set_first_user
    # The first user we create has an admin role and uses the configuration API key
    if User.count == 0 && !Rails.env.test?
      self.role = "admin"
      self.authentication_token = ENV['API_KEY']
    end
  end

  # Don't require email or password, as we also use OAuth
  def email_required?
    false
  end

  def password_required?
    false
  end

  # Attempt to find a user by it's email. If a record is found, send new
  # password instructions to it. If not user is found, returns a new user
  # with an email not found error.
  def self.send_reset_password_instructions(attributes={})
    recoverable = find_recoverable_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
    recoverable.send_reset_password_instructions if recoverable.persisted?
    recoverable
  end

  def self.find_recoverable_or_initialize_with_errors(required_attributes, attributes, error=:invalid)
    (case_insensitive_keys || []).each { |k| attributes[k].try(:downcase!) }

    attributes = attributes.slice(*required_attributes)
    attributes.delete_if { |key, value| value.blank? }

    if attributes.size == required_attributes.size
      record = where(attributes).first
    end

    unless record
      record = new

      required_attributes.each do |key|
        value = attributes[key]
        record.send("#{key}=", value)
        record.errors.add(key, value.present? ? error : :blank)
      end
    end
    record
  end

  def ensure_authentication_token
    self.authentication_token = generate_authentication_token if authentication_token.blank?
  end

  private

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  rescue_from ActiveRecord::RecordInvalid do |exception|
    redirect_to root_path, :alert => exception.message
  end

  def failure
    flash[:alert] = "Error signing in with #{ENV['OMNIAUTH']}"
    redirect_to root_path
  end

  # generic handler for all omniauth providers
  def action_missing(provider)
    auth = request.env["omniauth.auth"]

    # provider-specific tweaks to standard omniauth hash
    case provider
    when "cas"
      auth.info.name = auth.extra.name
      auth.info.email = auth.extra.email
    end

    @user = User.from_omniauth(auth)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      flash[:alert] = @user.errors.map { |k,v| "#{k}: #{v}" }.join("<br />").html_safe || "Error signing in with #{provider}"
      redirect_to root_path
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def new
    redirect_to new_user_session_path if User.count > 0
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:password, :password_confirmation, :name, :email, :remember_me) }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_user, only: [:show, :edit, :destroy]
  load_and_authorize_resource

  def show
    respond_to do |format|
      format.js { render :show }
      format.html
    end
  end

  def index
    load_index
  end

  def edit
    if params[:id].to_i == current_user.id
      # user updates his account
      render :show
    else
      # admin updates user account
      @user = User.find(params[:id])
      @reports = Report.available(@user.role)
      @doc = Doc.find("api")
      load_index
      render :index
    end
  end

  def update
    if params[:id].to_i == current_user.id
      # user updates his account

      load_user

      if params[:user][:subscribe]
        report = Report.find(params[:user][:subscribe])
        @user.reports << report
      elsif params[:user][:unsubscribe]
        report = Report.find(params[:user][:unsubscribe])
        @user.reports.delete(report)
      else
        sign_in @user, :bypass => true if @user.update_attributes(safe_params)
      end

      render :show
    else
      # admin updates user account
      @user = User.find(params[:id])
      @user.update_attributes(safe_params)

      load_index
      render :index
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    load_index
    render :index
  end

  def update_password
    load_user
    if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to root_path
    else
      render "edit"
    end
  end

  protected

  def load_user
    if user_signed_in?
      @user = current_user
      @reports = Report.available(@user.role)
      @doc = Doc.find("api")
    else
      fail CanCan::AccessDenied.new("Please sign in first.", :read, User)
    end
  end

  def load_index
    collection = User
    if params[:role]
      collection = collection.where(:role => params[:role])
      @role = params[:role]
    end
    collection = collection.query(params[:query]) if params[:query]
    collection = collection.ordered

    @users = collection.paginate(:page => params[:page])
  end

  private

  def safe_params
    params.require(:user).permit(:name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :subscribe,
                                 :unsubscribe,
                                 :role,
                                 :publisher_id,
                                 :authentication_token)
  end
end

app/views/users/_index.html.erb
<div class="page-header clearfix">
   <div class="btn-toolbar pull-right">
    <div class="btn-group btn-group-sm">
      <%= link_to "#{icon("dashboard")} API Requests".html_safe, api_requests_path, { id: "api_requests", class: "btn btn-default" } %>
    </div>
  </div>
  <h1 class="pull-left">Users</h1>

  <%= form_tag(users_path, :method => "get", :class => "form-inline text-center", :role => "form") do %>
    <div class="form-group">
      <%= search_field_tag :query, params[:query], :placeholder => "Search", :class => "form-control" %>
    </div>
    <button type="submit" class="btn btn-default hidden-xs"><%= icon("search") %></button>
    <% unless params[:query].blank? %>
      <%= link_to "clear", users_path(:role => params[:role]), :class => "btn" %>
    <% end %>
  <% end %>
</div>

<div class="work">&nbsp;
  <div class="btn-toolbar pull-left">
    <div class="btn-group btn-group-sm">
      <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"><%= icon("filter") %> <%= @role.nil? ? "All Roles" : @role.capitalize %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All Roles", users_path(:query => params[:query]) %></li>
        <li class="divider"></li>
        <% roles.each do|role| %>
        <li><%= link_to h(role.capitalize), users_path(:role => role, :query => params[:query]) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% if @users.size > 0 %>
  <div class="panel-group" id="user">
    <% @users.each do |user| %>
      <div class="panel panel-default">
        <div class="panel-heading panel-title panel-list">
          <%= link_to ("#{h(user.name)}<small class='pull-right'>#{user.last_sign_in_at.blank? ? "" : user.last_sign_in_at.to_s(:short)}</small>").html_safe, "#user_#{user.id}", :class => "accordion-toggle", :id => "link_#{user.id}", :data => { :toggle => "collapse", :parent => "#user" }, :href => "#user_#{user.id}" %>
        </div>
        <% if can?(:manage, user) && @user && @user.id == user.id && (controller.action_name == "edit" or (controller.action_name == "update" and !@user.errors.empty?)) %>
          <div id="user_<%= user.id %>" class="panel-collapse collapse.in">
            <div class="panel-body">
              <%= simple_form_for user, url: user_path(user), html: { role: "form", remote: true } do |f| %>
                <%= f.input :authentication_token, label: "API key", input_html: { class: "form-user" } %>
                <%= f.input :role, collection: roles.map { |role| [role.titleize, role] }, include_blank: false, input_html: { class: "form-user" } %>
                <%= f.association :publisher, collection: Publisher.order('title').map { |publisher| [publisher.title, publisher.member_id] }, input_html: { class: "form-user" } %>

                <div class="form-group">
                  <%= f.submit "Save ", class: "btn btn-default" %>
                  <%= link_to 'Cancel', users_path(query: params[:query], role: params[:role]), { :remote => true, :class => 'btn' } %>
                </div>
              <% end %>
            </div>
          </div>
        <% else %>
          <div id="user_<%= user.id %>" class="panel-collapse collapse">
            <div class="panel-body">
              <% if can?(:manage, user) && user.id != current_user.id %>
                <div class="btn-toolbar pull-right">
                  <div class="btn-group btn-group-sm">
                    <%= link_to icon("pencil").html_safe, edit_user_path(user, query: params[:query], role: params[:role]), remote: true, class: 'btn btn-default btn-sm', id: "#{user.id}-edit" %>
                  </div>
                  <div class="btn-group btn-group-sm">
                    <%= link_to icon("trash").html_safe, user_path(user, query: params[:query], role: params[:role]), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: 'btn btn-default btn-sm', id: "#{user.id}-delete" %>
                  </div>
                </div>
              <% end %>

              <% if user.email.present? %>
                <h5>Email</h5>
                <%= link_to h(user.email), "mailto:#{user.email}" %>
              <% end %>

              <h5>API key</h5>
              <%= link_to user.authentication_token, api_requests_path(q: user.authentication_token) %>

              <h5>Role</h5>
              <%= user.role.capitalize %>

              <% if user.publisher %>
                <h5>Publisher</h5>
                <%= link_to h(user.publisher.title), publisher_path(user.publisher_id) %>
              <% end %>

              <h5>Account created</h5>
              <%= user.created_at.to_s(:friendly) %>

              <h5>Sign in count</h5>
              <%= user.sign_in_count %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="text-center">
    <%= will_paginate @users, :params => { :controller => users_path }, :renderer => BootstrapPagination::Rails %>
  </div>
<% else %>
  <div class="alert alert-info">There are currently no users
    <% unless @role.nil? %>
        with role "<%= @role.capitalize %>"
    <% end %>
    <% unless params[:query].blank? %>
        with <em><%= params[:query] %></em> in the name, email or API key
    <% end %>
  </div>
<% end %>

app/views/users/_reports.html.erb
<% if @reports.size > 0 %>
  <div class="panel-group" id="report">
    <% @reports.each do |report| %>
      <div class="panel <%= report.users.exists?(@user) ? 'panel-info' : 'panel-default' %>">
        <div class="panel-heading panel-title panel-list">
          <%= link_to report.display_name, "#report_#{report.id}", :class => "accordion-toggle", :id => "link_#{report.id}", :data => { :toggle => "collapse", :parent => "#report" }, :href => "#report_#{report.id}" %>
          <% if report.users.exists?(@user) %><span class="label label-report pull-right">subscribed</span><% end %>
        </div>
        <div id="report_<%= report.id %>" class="panel-collapse collapse">
          <div class="panel-body">
            <div class="btn-toolbar pull-right">
              <div class="btn-group btn-group-sm">
                <% if report.users.exists?(@user) %>
                  <%= link_to 'Unsubscribe'.html_safe, user_path(@user, :user => { :unsubscribe => report.id }), :method => :put, :remote => true, :class => 'btn btn-default btn-sm', :id => "#{report.name}-status" %>
                <% else %>
                  <%= link_to 'Subscribe'.html_safe, user_path(@user, :user => { :subscribe => report.id }), :method => :put, :remote => true, :class => 'btn btn-info btn-sm', :id => "#{report.name}-status" %>
                <% end %>
              </div>
            </div>

            <% if report.users.exists?(@user) %>
              <p><%= description_with_link(report).html_safe %>
            <% else %>
              <p><%= report.description %>
            <% end %>
            <% if report.interval %>
              , interval <%= distance_of_time_in_words(Time.now, Time.now + report.interval, true, { :highest_measure_only => true }) %>
            <% end %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="alert alert-info">There are currently no reports</div>
<% end %>

app/views/users/_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading panel-title">
    <% if can?(:create, User) && controller.action_name != "edit" && !(controller.action_name == "update" && !@user.errors.empty?) %>
      <span class="pull-right">
         <%= link_to icon("pencil").html_safe, edit_user_path(@user), { remote: true, class: 'btn btn-default btn-sm', id: 'edit' } %>
      </span>
    <% end %>
    Your Account
  </div>
  <div class="panel-body">
    <% if can?(:create, User) && (controller.action_name == "edit" || (controller.action_name == "update" && !@user.errors.empty?)) %>
      <%= simple_form_for @user, :url => user_path(@user), :html => { :remote => true } do |f| %>
          <%= f.input :name, input_html: { class: "form-user" } %>
          <%= f.input :authentication_token, label: "API key", input_html: { class: "form-user" } %>
          <% if ENV['OMNIAUTH'] == "orcid" %>
            <%= f.input :email, input_html: { class: "form-user" } %>
          <% end %>
          <%= f.input :password, input_html: { class: "form-user" } %>
          <%= f.input :password_confirmation, input_html: { class: "form-user" } %>
          <% if Publisher.first %>
            <%= f.association :publisher, collection: Publisher.order('title').map { |publisher| [publisher.title, publisher.member_id] }, input_html: { class: "form-user" } %>
          <% end %>

          <div class="form-group">
            <%= f.submit "Save ", class: "btn btn-default" %>
            <%= link_to 'Cancel', user_path(@user), { remote: true, class: 'btn' } %>
          </div>
      <% end %>
    <% else %>
      <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd><%= @user.name %></dd>
        <% if @user.email.present? %>
          <dt>Email</dt>
          <dd><%= @user.email %></dd>
        <% end %>
        <dt>Role</dt>
        <% if @user.role == "admin" %>
          <dd>Admin - full access to the ALM application</dd>
        <% elsif @user.role == "staff" %>
          <dd>Staff - read access to the admin dashboard</dd>
        <% else %>
          <dd>User - read access to the API</dd>
        <% end %>
        <% if can?(:create, User) && @user.publisher %>
          <dt>Publisher</dt>
          <dd><%= link_to h(@user.publisher.title), publisher_path(@user.publisher.member_id) %></dd>
        <% end %>
        <dt>API Key</dt>
        <dd><%= @user.authentication_token %></dd>
      </dl>
    <% end %>
  </div>
</div>

<ul class="nav nav-pills">
  <li class="active"><a href="#reports" data-toggle="tab">Reports</a></li>
  <li><a href="#documentation" data-toggle="tab" title="Documentation">Documentation</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="reports">
    <%= render :partial => 'reports' %>
  </div>
  <div class="tab-pane" id="documentation">
    <%= render :partial => 'docs/show' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content" id="index">
  <%= render :partial => 'index' %>
</div>

app/views/users/index.js.erb
$('#index').html("<%= escape_javascript(render "index") %>");

app/views/users/show.js.erb
$('#show').html("<%= escape_javascript(render "show") %>");
$('#reports').html("<%= escape_javascript(render "reports") %>");